version: '3.9'

services:
  backend:
    build:
      context: ./backend
    command: python /backend/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - database
  
  database:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: